# TODO
* Handle pre-set user/app tokens
    * Anything dealing with messages can use those values if they are not given as arguments (and have been set)
    * Function to validate a user key with regexp. is.legal_key? Use in message validator and in set_key
    * Add info about new functions in message documentation
    * Document new functions
    * Now, the only absolutely necessary arg to sending is the message. Handle the rest with ...?
        * Do this in the PushoverMessage() constructor
        * Do this in the pushover_* helper functions
* Should helper functions just return a Response object?
* contents() is an R(Hmisc) thing. Rename? Or add a new method? get()?
* function to get sounds (not from server, just from list)?

# If you ever talk to Pushover
* Can they provide a token, user, receipt, request that can be used for working examples?
* API Version returned in queries
* Validate a user/group key


# TODO for release
* Put on GitHub
* Better instructions for install_github
    * how to do master?
    * how to do a specific version?
    * do dependencies get installed?
* submit to CRAN
* vignette? blog post? both?
* submit to rbloggers?
    * Can get RSS for specific category/tag: https://codex.wordpress.org/WordPress_Feeds#Post-specific_comment_feed
